### ISSUE TITLE
regarding dataset

### ISSUE THREAD

**Issue by abhishekkritarth** [GauravWaghmare/Phoneme#2]
Hi  @GauravWaghmare,

I have gone through your code.I didn't find the data which is required to run this code.
Can you please send me the links of Data-set or at-least please specify the format of sample Data-set applicable for this code.

Thanks and Regards

**Comment by GauravWaghmare** [comment]
Unfortunately, we don't have the dataset with us. 
The structure of the training data is 

TrainRoot
| _ User1
    - 1.wav
    - 2.wav 
| _ User2
    - 1.wav
    - 2.wav

It can be any number of wav files in a directory, and any number of users. You can configure that in the code.

**Comment by abhishekkritarth** [comment]
while running the code by giving sample .wav files, I am getting the following error. Can you please give me any suggestion to resolve this,

Speaker No. = 1
/home/mcis-lap-23/PycharmProjects/Text2Speech/Speaker-Identification-master/data/1/
('fname :', '/home/mcis-lap-23/PycharmProjects/Text2Speech/Speaker-Identification-master/data/1/a0053.wav')
512.0
single column
Traceback (most recent call last):
  File "/home/mcis-lap-23/PycharmProjects/Text2Speech/Speaker-Identification-master/runMode_1.py", line 216, in <module>
    tot_positives = t.test(testdirec)
  File "/home/mcis-lap-23/PycharmProjects/Text2Speech/Speaker-Identification-master/runMode_1.py", line 151, in test
    pca = self.train()
  File "/home/mcis-lap-23/PycharmProjects/Text2Speech/Speaker-Identification-master/runMode_1.py", line 123, in train
    train_data = self.featuresObj.load_data()
  File "/home/mcis-lap-23/PycharmProjects/Text2Speech/Speaker-Identification-master/runMode_1.py", line 80, in load_data
    X, Y = self.getTrainingMatrix()
  File "/home/mcis-lap-23/PycharmProjects/Text2Speech/Speaker-Identification-master/runMode_1.py", line 41, in getTrainingMatrix
    featuresT = self.getFeaturesFromWave(fname)
  File "/home/mcis-lap-23/PycharmProjects/Text2Speech/Speaker-Identification-master/runMode_1.py", line 68, in getFeaturesFromWave
    segmentLimits = rs.silenceRemoval(signal, fs, self.frame_size, self.frame_shift)
  File "/home/mcis-lap-23/PycharmProjects/Text2Speech/Speaker-Identification-master/Removesilence.py", line 159, in silenceRemoval
    SVM = trainSVM(featuresNormSS, 1.0)                               # train the respective SVM probabilistic model (ONSET vs SILENCE)
  File "/home/mcis-lap-23/PycharmProjects/Text2Speech/Speaker-Identification-master/Removesilence.py", line 70, in trainSVM
    svmm = mlpy.LibSvm(svm_type='c_svc', kernel_type='linear', eps=0.0000001, C=Cparam, probability=True)
AttributeError: 'module' object has no attribute 'LibSvm'

**Comment by dalmam11** [comment]
same error with abhishekkritarth

**Comment by joony0123** [comment]
I had that one too but I was able to fix it by downloading mlpy 3.4 version using setup.py after downloading from SourceForge on Linux. For some reason pip install mlpy is not compatible with the code's mlpy

**Comment by Aurora11111** [comment]
@GauravWaghmare how to set the epoch when I trianing about 300 speaker,and how much speech per person need?
